-- Generado por Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   en:        2023-02-20 11:35:12 CET
--   sitio:      SQL Server 2012
--   tipo:      SQL Server 2012



CREATE TABLE CLIENTE 
    (
     ID_CLIENTE INTEGER NOT NULL , 
     NOMBRE VARCHAR (50) NOT NULL , 
     CIF VARCHAR (9) NOT NULL , 
     TIPO_CLIENTE_ID_TIPO_CLIENTE INTEGER NOT NULL , 
     DIRECCION VARCHAR (50) NOT NULL , 
     CONCELLO_CP INTEGER NOT NULL 
    )
GO 

CREATE UNIQUE NONCLUSTERED INDEX 
    CLIENTE__IDX ON CLIENTE 
    ( 
     CONCELLO_CP 
    ) 
GO 


CREATE UNIQUE NONCLUSTERED INDEX 
    CLIENTE__IDXv1 ON CLIENTE 
    ( 
     TIPO_CLIENTE_ID_TIPO_CLIENTE 
    ) 
GO

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY CLUSTERED (ID_CLIENTE)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CONCELLO 
    (
     CP INTEGER NOT NULL , 
     CONCELLO VARCHAR (20) NOT NULL ,
	 PROVINCIA VARCHAR (20) NOT NULL
    )
GO

ALTER TABLE CONCELLO ADD CONSTRAINT CONCELLO_PK PRIMARY KEY CLUSTERED (CP)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CONTACTO_CLIENTE 
    (
     ID_CONTACTO_CLIENTE INTEGER NOT NULL , 
     NOMBRE VARCHAR (20) NOT NULL , 
     APELLIDO_1 VARCHAR (20) NOT NULL , 
     APELLIDO_2 VARCHAR (20) , 
     CLIENTE_ID_CLIENTE INTEGER NOT NULL 
    )
GO

ALTER TABLE CONTACTO_CLIENTE ADD CONSTRAINT CONTACTO_CLIENTE_PK PRIMARY KEY CLUSTERED (ID_CONTACTO_CLIENTE)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CORREO_ELECTRONICO 
    (
     MAIL VARCHAR (40) NOT NULL , 
     CLIENTE_ID_CLIENTE INTEGER NOT NULL , 
     PROVEEDOR_ID_PROVEEDOR INTEGER NOT NULL , 
     EMPLEADO_ID_EMPLEADO INTEGER NOT NULL , 
     CONTACTO_CLIENTE_ID_CONTACTO_CLIENTE INTEGER NOT NULL 
    )
GO

ALTER TABLE CORREO_ELECTRONICO ADD CONSTRAINT CORREO_ELECTRONICO_PK PRIMARY KEY CLUSTERED (MAIL)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE EMPLEADO 
    (
     ID_EMPLEADO INTEGER NOT NULL , 
     NIF VARCHAR (9) NOT NULL , 
     PUESTO_ID_PUESTO INTEGER NOT NULL , 
     NOMBRE VARCHAR (20) NOT NULL , 
     APELLIDO_1 VARCHAR (20) NOT NULL , 
     APELLIDO_2 VARCHAR (20) , 
     DIRECCION VARCHAR (50) NOT NULL , 
     CONCELLO_CP INTEGER NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    EMPLEADO__IDX ON EMPLEADO 
    ( 
     CONCELLO_CP 
    ) 
GO 


CREATE UNIQUE NONCLUSTERED INDEX 
    EMPLEADO__IDXv1 ON EMPLEADO 
    ( 
     PUESTO_ID_PUESTO 
    ) 
GO

ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_PK PRIMARY KEY CLUSTERED (ID_EMPLEADO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE EVENTO 
    (
     ID_EVENTO INTEGER NOT NULL , 
     CLIENTE_ID_CLIENTE INTEGER NOT NULL , 
     NOMBRE_EVENTO VARCHAR (30) NOT NULL , 
     FECHA_INICIO DATE NOT NULL , 
     FECHA_FIN DATE NOT NULL , 
     NOMBRE_LUGAR VARCHAR (30) , 
     DIRECCION VARCHAR (50) NOT NULL , 
     CONCELLO_CP INTEGER NOT NULL , 
     DESCRIPCION_EVENTO TEXT , 
     OBSERVACIONES TEXT 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    EVENTO__IDX ON EVENTO 
    ( 
     CONCELLO_CP 
    ) 
GO

ALTER TABLE EVENTO ADD CONSTRAINT EVENTO_PK PRIMARY KEY CLUSTERED (ID_EVENTO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE MARCA 
    (
     MARCA VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE MARCA ADD CONSTRAINT MARCA_PK PRIMARY KEY CLUSTERED (MARCA)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE MATERIAL_INVENTARIO 
    (
     ID_ITEM INTEGER NOT NULL , 
     FECHA_ENTRADA DATE NOT NULL , 
     ID_FACTURA INTEGER NOT NULL , 
     PROVEEDOR_ID_PROVEEDOR INTEGER NOT NULL 
    )
GO

ALTER TABLE MATERIAL_INVENTARIO ADD CONSTRAINT MATERIAL_INVENTARIO_PK PRIMARY KEY CLUSTERED (ID_ITEM)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE MODELO 
    (
     MATERIAL_INVENTARIO_ID_ITEM INTEGER NOT NULL , 
     MODELO VARCHAR (20) NOT NULL , 
     TIPO_MATERIAL_ID_TIPO INTEGER NOT NULL , 
     MARCA_MARCA VARCHAR (20) NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    MODELO__IDX ON MODELO 
    ( 
     TIPO_MATERIAL_ID_TIPO 
    ) 
GO

ALTER TABLE MODELO ADD CONSTRAINT MODELO_PK PRIMARY KEY CLUSTERED (MODELO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE PROVEEDOR 
    (
     ID_PROVEEDOR INTEGER NOT NULL , 
     NOMBRE VARCHAR (50) NOT NULL , 
     CIF VARCHAR (9) NOT NULL , 
     DIRECCION VARCHAR (50) NOT NULL , 
     CONCELLO_CP INTEGER NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    PROVEEDOR__IDX ON PROVEEDOR 
    ( 
     CONCELLO_CP 
    ) 
GO

ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY CLUSTERED (ID_PROVEEDOR)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE PUESTO 
    (
     ID_PUESTO INTEGER NOT NULL , 
     NOMBRE_PUESTO VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE PUESTO ADD CONSTRAINT PUESTO_PK PRIMARY KEY CLUSTERED (ID_PUESTO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE RIDER_TECNICO 
    (
     ID_RIDER INTEGER NOT NULL , 
     RIDER VARBINARY NOT NULL , 
     FECHA_ENVIO DATE , 
     EVENTO_ID_EVENTO INTEGER NOT NULL 
    )
GO

ALTER TABLE RIDER_TECNICO ADD CONSTRAINT RIDER_TECNICO_PK PRIMARY KEY CLUSTERED (ID_RIDER)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE SUPERVISA 
    (
     EMPLEADO_ID_EMPLEADO INTEGER NOT NULL , 
     EVENTO_ID_EVENTO INTEGER NOT NULL 
    )
GO

CREATE TABLE TELEFONO 
    (
     TLF INTEGER NOT NULL , 
     CLIENTE_ID_CLIENTE INTEGER NULL , 
     PROVEEDOR_ID_PROVEEDOR INTEGER NULL , 
     EMPLEADO_ID_EMPLEADO INTEGER NULL , 
     CONTACTO_CLIENTE_ID_CONTACTO_CLIENTE INTEGER NULL 
    )
GO

ALTER TABLE TELEFONO ADD CONSTRAINT TELEFONO_PK PRIMARY KEY CLUSTERED (TLF)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE TIPO_CLIENTE 
    (
     ID_TIPO_CLIENTE INTEGER NOT NULL , 
     TIPO VARCHAR NOT NULL 
    )
GO

ALTER TABLE TIPO_CLIENTE ADD CONSTRAINT TIPO_CLIENTE_PK PRIMARY KEY CLUSTERED (ID_TIPO_CLIENTE)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE TIPO_MATERIAL 
    (
     ID_TIPO INTEGER NOT NULL , 
     TIPO VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE TIPO_MATERIAL ADD CONSTRAINT TIPO_MATERIAL_PK PRIMARY KEY CLUSTERED (ID_TIPO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE CLIENTE 
    ADD CONSTRAINT CLIENTE_CONCELLO_FK FOREIGN KEY 
    ( 
     CONCELLO_CP
    ) 
    REFERENCES CONCELLO 
    ( 
     CP 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CLIENTE 
    ADD CONSTRAINT CLIENTE_TIPO_CLIENTE_FK FOREIGN KEY 
    ( 
     TIPO_CLIENTE_ID_TIPO_CLIENTE
    ) 
    REFERENCES TIPO_CLIENTE 
    ( 
     ID_TIPO_CLIENTE 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CONTACTO_CLIENTE 
    ADD CONSTRAINT CONTACTO_CLIENTE_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_ID_CLIENTE
    ) 
    REFERENCES CLIENTE 
    ( 
     ID_CLIENTE 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CORREO_ELECTRONICO 
    ADD CONSTRAINT CORREO_ELECTRONICO_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_ID_CLIENTE
    ) 
    REFERENCES CLIENTE 
    ( 
     ID_CLIENTE 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CORREO_ELECTRONICO 
    ADD CONSTRAINT CORREO_ELECTRONICO_CONTACTO_CLIENTE_FK FOREIGN KEY 
    ( 
     CONTACTO_CLIENTE_ID_CONTACTO_CLIENTE
    ) 
    REFERENCES CONTACTO_CLIENTE 
    ( 
     ID_CONTACTO_CLIENTE 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CORREO_ELECTRONICO 
    ADD CONSTRAINT CORREO_ELECTRONICO_EMPLEADO_FK FOREIGN KEY 
    ( 
     EMPLEADO_ID_EMPLEADO
    ) 
    REFERENCES EMPLEADO 
    ( 
     ID_EMPLEADO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CORREO_ELECTRONICO 
    ADD CONSTRAINT CORREO_ELECTRONICO_PROVEEDOR_FK FOREIGN KEY 
    ( 
     PROVEEDOR_ID_PROVEEDOR
    ) 
    REFERENCES PROVEEDOR 
    ( 
     ID_PROVEEDOR 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EMPLEADO 
    ADD CONSTRAINT EMPLEADO_CONCELLO_FK FOREIGN KEY 
    ( 
     CONCELLO_CP
    ) 
    REFERENCES CONCELLO 
    ( 
     CP 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EMPLEADO 
    ADD CONSTRAINT EMPLEADO_PUESTO_FK FOREIGN KEY 
    ( 
     PUESTO_ID_PUESTO
    ) 
    REFERENCES PUESTO 
    ( 
     ID_PUESTO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EVENTO 
    ADD CONSTRAINT EVENTO_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_ID_CLIENTE
    ) 
    REFERENCES CLIENTE 
    ( 
     ID_CLIENTE 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EVENTO 
    ADD CONSTRAINT EVENTO_CONCELLO_FK FOREIGN KEY 
    ( 
     CONCELLO_CP
    ) 
    REFERENCES CONCELLO 
    ( 
     CP 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MATERIAL_INVENTARIO 
    ADD CONSTRAINT MATERIAL_INVENTARIO_PROVEEDOR_FK FOREIGN KEY 
    ( 
     PROVEEDOR_ID_PROVEEDOR
    ) 
    REFERENCES PROVEEDOR 
    ( 
     ID_PROVEEDOR 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MODELO 
    ADD CONSTRAINT MODELO_MARCA_FK FOREIGN KEY 
    ( 
     MARCA_MARCA
    ) 
    REFERENCES MARCA 
    ( 
     MARCA 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MODELO 
    ADD CONSTRAINT MODELO_MATERIAL_INVENTARIO_FK FOREIGN KEY 
    ( 
     MATERIAL_INVENTARIO_ID_ITEM
    ) 
    REFERENCES MATERIAL_INVENTARIO 
    ( 
     ID_ITEM 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MODELO 
    ADD CONSTRAINT MODELO_TIPO_MATERIAL_FK FOREIGN KEY 
    ( 
     TIPO_MATERIAL_ID_TIPO
    ) 
    REFERENCES TIPO_MATERIAL 
    ( 
     ID_TIPO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PROVEEDOR 
    ADD CONSTRAINT PROVEEDOR_CONCELLO_FK FOREIGN KEY 
    ( 
     CONCELLO_CP
    ) 
    REFERENCES CONCELLO 
    ( 
     CP 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RIDER_TECNICO 
    ADD CONSTRAINT RIDER_TECNICO_EVENTO_FK FOREIGN KEY 
    ( 
     EVENTO_ID_EVENTO
    ) 
    REFERENCES EVENTO 
    ( 
     ID_EVENTO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SUPERVISA 
    ADD CONSTRAINT SUPERVISA_EMPLEADO_FK FOREIGN KEY 
    ( 
     EMPLEADO_ID_EMPLEADO
    ) 
    REFERENCES EMPLEADO 
    ( 
     ID_EMPLEADO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SUPERVISA 
    ADD CONSTRAINT SUPERVISA_EVENTO_FK FOREIGN KEY 
    ( 
     EVENTO_ID_EVENTO
    ) 
    REFERENCES EVENTO 
    ( 
     ID_EVENTO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TELEFONO 
    ADD CONSTRAINT TELEFONO_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_ID_CLIENTE
    ) 
    REFERENCES CLIENTE 
    ( 
     ID_CLIENTE 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TELEFONO 
    ADD CONSTRAINT TELEFONO_CONTACTO_CLIENTE_FK FOREIGN KEY 
    ( 
     CONTACTO_CLIENTE_ID_CONTACTO_CLIENTE
    ) 
    REFERENCES CONTACTO_CLIENTE 
    ( 
     ID_CONTACTO_CLIENTE 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TELEFONO 
    ADD CONSTRAINT TELEFONO_EMPLEADO_FK FOREIGN KEY 
    ( 
     EMPLEADO_ID_EMPLEADO
    ) 
    REFERENCES EMPLEADO 
    ( 
     ID_EMPLEADO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TELEFONO 
    ADD CONSTRAINT TELEFONO_PROVEEDOR_FK FOREIGN KEY 
    ( 
     PROVEEDOR_ID_PROVEEDOR
    ) 
    REFERENCES PROVEEDOR 
    ( 
     ID_PROVEEDOR 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             7
-- ALTER TABLE                             38
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
